SELECT NOME, CHARINDEX(' ', NOME) FROM [TABELA DE CLIENTES]

SELECT NOME, CHARINDEX(' ', NOME), SUBSTRING(NOME, 1, CHARINDEX(' ', NOME) - 1) FROM [TABELA DE CLIENTES]


DECLARE @CPF VARCHAR(50);
DECLARE @NOME VARCHAR(100);
DECLARE @DATA_NASCIMENTO DATE; 
DECLARE @IDADE INT;

SET @CPF = '2600586709';

SELECT @NOME = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT 'O primeiro nome do cliente ' + @NOME + ', cujo CPF é ' + @CPF + ', corresponde a ' + SUBSTRING(@NOME, 1, CHARINDEX(' ', @NOME) - 1);
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;


