SELECT * FROM [TABELA DE CLIENTES]

SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY BAIRRO

SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = 'Água Santa'

DECLARE @LIMITE_MAXIMO FLOAT;
--DECLARE @LIMITE_ATUAL FLOAT;
DECLARE @BAIRRO VARCHAR(20);

SET @LIMITE_MAXIMO = 50000;
SET @BAIRRO = 'Água Santa';

IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)
PRINT 'VALOR ESTOUROU';
ELSE
PRINT 'VALOR NÃO ESTOUROU';





