DECLARE @CPF VARCHAR (50);
DECLARE @NOME VARCHAR (100);
DECLARE @DATA_DE_NASCIMENTO DATE;
DECLARE @IDADE INT;

--SELECT * FROM [TABELA DE CLIENTES] WHERE CPF = '19290992743'; -- PARA VER SE JÁ FOI ATRIBUIDO ALGUM VALOR

SET @CPF = '19290992743'; -- ATRIBUINDO UMA VARIAVEL NO CAMPO QUE JÁ FOI CRIADO


SELECT @NOME = NOME, @DATA_DE_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE FROM [TABELA DE CLIENTES] WHERE CPF = @CPF;

PRINT @NOME;
PRINT @CPF;
PRINT @DATA_DE_NASCIMENTO;
PRINT @IDADE;

SELECT * FROM [TABELA DE CLIENTES]