DECLARE @NUMERO_INICIAL_SEQUENCIA INT, @NUMERO_FINAL_SEQUENCIA INT;
DECLARE @TESTE_NOTA_FISCAL INT;
DECLARE @TABELA_DE_NUMEROS TABLE ([NUMERO] INT, [STATUS] VARCHAR(20));
CREATE TABLE #TABELA_DE_NUMEROS ([NUMERO] INT, [STATUS] VARCHAR(20));

SET @NUMERO_INICIAL_SEQUENCIA = 1;
SET @NUMERO_FINAL_SEQUENCIA = 200;

WHILE @NUMERO_INICIAL_SEQUENCIA <= @NUMERO_FINAL_SEQUENCIA

BEGIN
SELECT @TESTE_NOTA_FISCAL = COUNT(*) FROM [NOTAS FISCAIS] WHERE NUMERO = @NUMERO_INICIAL_SEQUENCIA;

IF @TESTE_NOTA_FISCAL = 1
BEGIN
INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');

INSERT INTO #TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
VALUES (@NUMERO_INICIAL_SEQUENCIA, 'É NOTA FISCAL');
END;
        
ELSE
BEGIN
INSERT INTO @TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃO É NOTA FISCAL');

INSERT INTO #TABELA_DE_NUMEROS ([NUMERO], [STATUS]) 
VALUES (@NUMERO_INICIAL_SEQUENCIA, 'NÃO É NOTA FISCAL');
END;

SET @NUMERO_INICIAL_SEQUENCIA = @NUMERO_INICIAL_SEQUENCIA + 1;
END;

SELECT * FROM @TABELA_DE_NUMEROS; -- DA ERRO
SELECT * FROM #TABELA_DE_NUMEROS; -- SENDO TEMPORARIA FUNCIONA O COMANDO SOMENTE NESTE ESPAÇO